/*
 * @Author: tohsaka888
 * @Date: 2022-09-19 09:28:41
 * @LastEditors: tohsaka888
 * @LastEditTime: 2022-09-19 09:28:41
 * @Description: 请填写简介
 */

import Head from 'next/head'
import React from 'react'

function CustomHead() {
  return (
    <Head>
      <title>程序员之家</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default CustomHead
