/*
 * @Author: tohsaka888
 * @Date: 2022-09-16 13:40:07
 * @LastEditors: tohsaka888
 * @LastEditTime: 2022-09-16 17:26:34
 * @Description: HomePage
 */
import { Loader } from '@react-three/drei'
import Slogan from 'components/HomePage/Slogan'
import LiveBackground from 'components/LiveBackground'
import { BackgroundContainer } from 'components/LiveBackground/index.style'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  const [move, setMove] = useState<boolean>(false)

  useEffect(() => {
    window.addEventListener('click', () => {
      setMove((m) => !m)
    })

    return () => {
      window.removeEventListener('click', () => {

      })
    }
  }, [])

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg" />
      <Slogan title={'常州工学院 程序员之家'} locale={'zh'} />
      <Slogan title={'The Home of Coder'} locale={'en'} />
      <BackgroundContainer>
        <LiveBackground />
      </BackgroundContainer>
      <div className="layer" />
      <Loader />
    </div>
  )
}

export default Home
